### PR TITLE
Update composer json for laravel 5.8

### PR DESCRIPTION
**Pull request by WhereIsLucas**

### CODE REVIEW

**Comment by yoeunes** [comment]
Thank you @WhereIsLucas ^^

**Comment by WhereIsLucas** [comment]
That was fast! 
It would be cool to put a version tag on it

**Comment by yoeunes** [comment]
done, could you please test it and let me know if everything work correctly,
thanks again

**Comment by WhereIsLucas** [comment]
Everything seems fine at first sight! Thanks for this awesome package!
I don't really what's wrong with the code formatting, how can I change ?

**Comment by yoeunes** [comment]
its okey I just clean up the code, Thanks for your PR ^^

**Pull request merged**
